# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='account_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Disabled'), (2, 'Basic'), (3, 'Admin')]),
        ),
    ]
