# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160208_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='manager',
            name='account_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Disabled'), (2, 'Pending'), (3, 'Basic'), (4, 'Admin')], default=2),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Manager'),
        ),
    ]
