# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 07:38
from __future__ import unicode_literals

import apps.bracketr.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('as_json', models.TextField(blank=True)),
                ('has_third_place', models.BooleanField(default=False)),
                ('is_double_elimination', models.BooleanField(default=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('header_image', models.ImageField(upload_to=apps.bracketr.models.make_path)),
                ('description', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('round_number', models.PositiveSmallIntegerField(default=0)),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Winner'), (2, 'Loser'), (3, 'Third'), (4, 'Round-robin'), (5, 'Winner-loser')], default=1)),
                ('number', models.PositiveSmallIntegerField(default=0)),
                ('team1_wins', models.PositiveSmallIntegerField(default=0)),
                ('team2_wins', models.PositiveSmallIntegerField(default=0)),
                ('team1_seed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team2_seed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracketr.Bracket')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('win', models.PositiveSmallIntegerField(default=0)),
                ('loss', models.PositiveSmallIntegerField(default=0)),
                ('header_path', models.ImageField(upload_to=apps.bracketr.models.make_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracketr.Bracket')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bracketr.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bracketr.Team'),
        ),
    ]
