# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 07:46
from __future__ import unicode_literals

import apps.bracketr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracketr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='header_image',
            field=models.ImageField(blank=True, upload_to=apps.bracketr.models.make_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='header_path',
            field=models.ImageField(blank=True, upload_to=apps.bracketr.models.make_path),
        ),
    ]
