# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracketr', '0002_auto_20160206_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='has_round_robin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bracket',
            name='is_randomized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='starting_seed',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
