# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracketr', '0003_auto_20160208_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='bracket',
            name='phase',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Round-robin'), (3, 'Bracket'), (4, 'Finished')], default=1),
        ),
    ]
