# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracketr', '0004_auto_20160208_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='starting_seed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
